# AUTOGENERATED! DO NOT EDIT! File to edit: 03_read_data.ipynb (unless otherwise specified).

__all__ = ['get_fpaths_lex', 'get_fpath_subr_yr', 'get_fpaths_subr_yrs', 'get_fpaths_yr', 'read_comm_csv',
           'read_comm_csvs', 'parse_dates']

# Cell
from glob import glob
import pandas as pd
from pathlib import Path
import os

# Cell
def get_fpaths_lex(LEX, CORPUS_DIR='data/', source='local', bucket_name='socemb'):
    if source == 'remote':
        client = storage.Client()
        blobs = [blob for blob in client.list_blobs(bucket_name, prefix=f'comments/{LEX}')]
        fpaths = [f'gs://{bucket_name}/{blob.name}' for blob in blobs]
    if source == 'local':
        lex_path = f'{CORPUS_DIR}{LEX}' + "/*.csv"
        fpaths = glob(lex_path)
    return fpaths

# Cell
def get_fpath_subr_yr(SUBREDDIT, YEAR, LIMIT):
    return f'data/subreddit/{SUBREDDIT}/{LIMIT}_{YEAR}.csv'

# Cell
def get_fpaths_subr_yrs(SUBREDDIT, LIMIT, YEARS):
    fpaths = [get_fpath_subr_yr(SUBREDDIT, LIMIT, year) for year in YEARS]
    return fpaths

# Cell
def get_fpaths_yr(YEAR, DIR='data/subreddit/'):
    fpaths = []
    for fpath in Path(DIR).rglob(f'*{YEAR}.csv'):
        fpaths.append(fpath)
    return fpaths

# Cell
def read_comm_csv(fpath):
    try:
        date_parser = lambda x: pd.to_datetime(x, unit='s', errors='coerce')
        comments = pd.read_csv(
            fpath,
            usecols=['id', 'created_utc', 'subreddit', 'body'],
            dtype={
                'id': 'string',
                'created_utc': int,
                'subreddit': 'string',
                'body': 'string'
            },
            parse_dates=['created_utc'],
            date_parser=date_parser,
            low_memory=False,
            lineterminator='\n'
        )
        comments_clean = comments\
            .dropna()\
            .drop_duplicates(subset='id')
        return comments_clean
    except FileNotFoundError:
        print(f'{fpath} not found on disk')
    except pd.errors.EmptyDataError:
        print(f'{fpath} is empty')

# Cell
def read_comm_csvs(fpaths):
    comments_lst = []
    for fpath in fpaths:
        comments = read_comm_csv(fpath)
        comments_lst.append(comments)
    comments_concat = pd.concat(
        comments_lst,
        axis=0,
        ignore_index=True
    )
    return comments_concat

# Cell
def parse_dates(comments):
    comments['created_utc'] = pd.to_datetime(comments['created_utc'], errors='coerce')
    comments.sort_values('created_utc', inplace=True)
    comments.dropna(subset=['created_utc'], inplace=True)
    return comments