# AUTOGENERATED! DO NOT EDIT! File to edit: 06_token_emb.ipynb (unless otherwise specified).

__all__ = ['proc_sentence']

# Cell
def proc_sentence(sent_string):
    sent = Sentence(sent_string)
    return sent