# AUTOGENERATED! DO NOT EDIT! File to edit: 07_type_emb.ipynb (unless otherwise specified).

__all__ = ['Corpus']

# Cell
class Corpus:
    """An iterator that yields sentences (lists of str)."""
    def __init__(self, docs_clean):
        self.docs_clean = docs_clean
    def __iter__(self):
        for doc in docs_clean:
            yield doc